from __future__ import annotations  # type: ignore
from unrealsdk import unreal
from typing import Any
import enum


class VoxelDataProvider(unreal.UObject): ...


class FluidSimDataProvider(unreal.UObject): ...


class QuickFluidVelocitySolverDataProvider(FluidSimDataProvider):

    def StepSim(self): ...
    def RunSim(self): ...
    def ResetSim(self): ...
    def InitSim(self): ...
    def ClearData(self): ...
