from __future__ import annotations # type: ignore
from unrealsdk import unreal
import typing
import enum


from . import core_uobject
from . import engine
from . import audio_mixer



class MediaSource(unreal.UObject):

    def Validate(self, ReturnValue: bool) -> bool: ...
    def GetUrl(self, ReturnValue: str) -> str: ...


class BaseMediaSource(MediaSource):
    PlayerName: str



class FileMediaSource(BaseMediaSource):
    FilePath: str
    PrecacheFile: bool
    def SetFilePath(self, Path: str): ...


class MediaAudioSinkProviderInterface(core_uobject.Interface): ...


class MediaBlueprintFunctionLibrary(engine.BlueprintFunctionLibrary):

    def EnumerateWebcamCaptureDevices(self, OutDevices: unreal.WrappedArray[MediaCaptureDevice], Filter: int): ...
    def EnumerateVideoCaptureDevices(self, OutDevices: unreal.WrappedArray[MediaCaptureDevice], Filter: int): ...
    def EnumerateAudioCaptureDevices(self, OutDevices: unreal.WrappedArray[MediaCaptureDevice], Filter: int): ...


class MediaPlayer(unreal.UObject):
    CacheAhead: core_uobject.Timespan
    CacheBehind: core_uobject.Timespan
    CacheBehindGame: core_uobject.Timespan
    NativeAudioOut: bool
    PlayOnOpen: bool
    Shuffle: bool
    Loop: bool
    Playlist: MediaPlaylist
    PlaylistIndex: int
    TimeDelay: core_uobject.Timespan
    HorizontalFieldOfView: float
    VerticalFieldOfView: float
    ViewRotation: core_uobject.Rotator
    PlayerGuid: core_uobject.Guid
    def SupportsSeeking(self, ReturnValue: bool) -> bool: ...
    def SupportsScrubbing(self, ReturnValue: bool) -> bool: ...
    def SupportsRate(self, Rate: float, Unthinned: bool, ReturnValue: bool) -> bool: ...
    def SetViewRotation(self, Rotation: core_uobject.Rotator, Absolute: bool, ReturnValue: bool) -> bool: ...
    def SetViewField(self, Horizontal: float, Vertical: float, Absolute: bool, ReturnValue: bool) -> bool: ...
    def SetVideoTrackFrameRate(self, TrackIndex: int, FormatIndex: int, FrameRate: float, ReturnValue: bool) -> bool: ...
    def SetTrackFormat(self, TrackType: EMediaPlayerTrack, TrackIndex: int, FormatIndex: int, ReturnValue: bool) -> bool: ...
    def SetTimeDelay(self, TimeDelay: core_uobject.Timespan): ...
    def SetRate(self, Rate: float, ReturnValue: bool) -> bool: ...
    def SetNativeVolume(self, Volume: float, ReturnValue: bool) -> bool: ...
    def SetLooping(self, Looping: bool, ReturnValue: bool) -> bool: ...
    def SetDesiredPlayerName(self, PlayerName: str): ...
    def SetBlockOnTime(self, Time: core_uobject.Timespan): ...
    def SelectTrack(self, TrackType: EMediaPlayerTrack, TrackIndex: int, ReturnValue: bool) -> bool: ...
    def Seek(self, Time: core_uobject.Timespan, ReturnValue: bool) -> bool: ...
    def Rewind(self, ReturnValue: bool) -> bool: ...
    def Reopen(self, ReturnValue: bool) -> bool: ...
    def Previous(self, ReturnValue: bool) -> bool: ...
    def Play(self, ReturnValue: bool) -> bool: ...
    def Pause(self, ReturnValue: bool) -> bool: ...
    def OpenUrl(self, URL: str, ReturnValue: bool) -> bool: ...
    def OpenSource(self, MediaSource: MediaSource, ReturnValue: bool) -> bool: ...
    def OpenPlaylistIndex(self, InPlaylist: MediaPlaylist, Index: int, ReturnValue: bool) -> bool: ...
    def OpenPlaylist(self, InPlaylist: MediaPlaylist, ReturnValue: bool) -> bool: ...
    def OpenFile(self, FilePath: str, ReturnValue: bool) -> bool: ...
    def Next(self, ReturnValue: bool) -> bool: ...
    def IsReady(self, ReturnValue: bool) -> bool: ...
    def IsPreparing(self, ReturnValue: bool) -> bool: ...
    def IsPlaying(self, ReturnValue: bool) -> bool: ...
    def IsPaused(self, ReturnValue: bool) -> bool: ...
    def IsLooping(self, ReturnValue: bool) -> bool: ...
    def IsConnecting(self, ReturnValue: bool) -> bool: ...
    def IsBuffering(self, ReturnValue: bool) -> bool: ...
    def HasError(self, ReturnValue: bool) -> bool: ...
    def GetViewRotation(self, ReturnValue: core_uobject.Rotator) -> core_uobject.Rotator: ...
    def GetVideoTrackType(self, TrackIndex: int, FormatIndex: int, ReturnValue: str) -> str: ...
    def GetVideoTrackFrameRates(self, TrackIndex: int, FormatIndex: int, ReturnValue: core_uobject.FloatRange) -> core_uobject.FloatRange: ...
    def GetVideoTrackFrameRate(self, TrackIndex: int, FormatIndex: int, ReturnValue: float) -> float: ...
    def GetVideoTrackDimensions(self, TrackIndex: int, FormatIndex: int, ReturnValue: core_uobject.IntPoint) -> core_uobject.IntPoint: ...
    def GetVideoTrackAspectRatio(self, TrackIndex: int, FormatIndex: int, ReturnValue: float) -> float: ...
    def GetVerticalFieldOfView(self, ReturnValue: float) -> float: ...
    def GetUrl(self, ReturnValue: str) -> str: ...
    def GetTrackLanguage(self, TrackType: EMediaPlayerTrack, TrackIndex: int, ReturnValue: str) -> str: ...
    def GetTrackFormat(self, TrackType: EMediaPlayerTrack, TrackIndex: int, ReturnValue: int) -> int: ...
    def GetTrackDisplayName(self, TrackType: EMediaPlayerTrack, TrackIndex: int, ReturnValue: str) -> str: ...
    def GetTimeDelay(self, ReturnValue: core_uobject.Timespan) -> core_uobject.Timespan: ...
    def GetTime(self, ReturnValue: core_uobject.Timespan) -> core_uobject.Timespan: ...
    def GetSupportedRates(self, OutRates: unreal.WrappedArray[core_uobject.FloatRange], Unthinned: bool): ...
    def GetSelectedTrack(self, TrackType: EMediaPlayerTrack, ReturnValue: int) -> int: ...
    def GetRate(self, ReturnValue: float) -> float: ...
    def GetPlaylistIndex(self, ReturnValue: int) -> int: ...
    def GetPlaylist(self, ReturnValue: MediaPlaylist) -> MediaPlaylist: ...
    def GetPlayerName(self, ReturnValue: str) -> str: ...
    def GetNumTracks(self, TrackType: EMediaPlayerTrack, ReturnValue: int) -> int: ...
    def GetNumTrackFormats(self, TrackType: EMediaPlayerTrack, TrackIndex: int, ReturnValue: int) -> int: ...
    def GetMediaName(self, ReturnValue: str) -> str: ...
    def GetHorizontalFieldOfView(self, ReturnValue: float) -> float: ...
    def GetDuration(self, ReturnValue: core_uobject.Timespan) -> core_uobject.Timespan: ...
    def GetDesiredPlayerName(self, ReturnValue: str) -> str: ...
    def GetAudioTrackType(self, TrackIndex: int, FormatIndex: int, ReturnValue: str) -> str: ...
    def GetAudioTrackSampleRate(self, TrackIndex: int, FormatIndex: int, ReturnValue: int) -> int: ...
    def GetAudioTrackChannels(self, TrackIndex: int, FormatIndex: int, ReturnValue: int) -> int: ...
    def Close(self): ...
    def CanPlayUrl(self, URL: str, ReturnValue: bool) -> bool: ...
    def CanPlaySource(self, MediaSource: MediaSource, ReturnValue: bool) -> bool: ...
    def CanPause(self, ReturnValue: bool) -> bool: ...


class MediaPlaylist(unreal.UObject):
    Items: unreal.WrappedArray[MediaSource]
    def Replace(self, Index: int, Replacement: MediaSource, ReturnValue: bool) -> bool: ...
    def RemoveAt(self, Index: int, ReturnValue: bool) -> bool: ...
    def Remove(self, MediaSource: MediaSource, ReturnValue: bool) -> bool: ...
    def Num(self, ReturnValue: int) -> int: ...
    def Insert(self, MediaSource: MediaSource, Index: int): ...
    def GetRandom(self, OutIndex: int, ReturnValue: MediaSource) -> MediaSource: ...
    def GetPrevious(self, InOutIndex: int, ReturnValue: MediaSource) -> MediaSource: ...
    def GetNext(self, InOutIndex: int, ReturnValue: MediaSource) -> MediaSource: ...
    def Get(self, Index: int, ReturnValue: MediaSource) -> MediaSource: ...
    def AddUrl(self, URL: str, ReturnValue: bool) -> bool: ...
    def AddFile(self, FilePath: str, ReturnValue: bool) -> bool: ...
    def Add(self, MediaSource: MediaSource, ReturnValue: bool) -> bool: ...


class MediaSoundComponent(audio_mixer.SynthComponent):
    Channels: EMediaSoundChannels
    DynamicRateAdjustment: bool
    RateAdjustmentFactor: float
    RateAdjustmentRange: core_uobject.FloatRange
    MediaPlayer: MediaPlayer
    def SetMediaPlayer(self, NewMediaPlayer: MediaPlayer): ...
    def GetMediaPlayer(self, ReturnValue: MediaPlayer) -> MediaPlayer: ...
    def BP_GetAttenuationSettingsToApply(self, OutAttenuationSettings: engine.SoundAttenuationSettings, ReturnValue: bool) -> bool: ...


class MediaTexture(engine.Texture):
    AddressX: int
    AddressY: int
    AutoClear: bool
    ClearColor: core_uobject.LinearColor
    MediaPlayer: MediaPlayer
    def SetMediaPlayer(self, NewMediaPlayer: MediaPlayer): ...
    def GetWidth(self, ReturnValue: int) -> int: ...
    def GetMediaPlayer(self, ReturnValue: MediaPlayer) -> MediaPlayer: ...
    def GetHeight(self, ReturnValue: int) -> int: ...
    def GetAspectRatio(self, ReturnValue: float) -> float: ...


class PlatformMediaSource(MediaSource):
    MediaSource: MediaSource



class StreamMediaSource(BaseMediaSource):
    StreamUrl: str



class TimeSynchronizableMediaSource(BaseMediaSource):
    bUseTimeSynchronization: bool



class MediaCaptureDevice:
    DisplayName: str
    URL: str



class EMediaWebcamCaptureDeviceFilter(enum.Enum):
    DepthSensor = 0
    Front = 1
    Rear = 2
    Unknown = 3


class EMediaVideoCaptureDeviceFilter(enum.Enum):
    Card = 0
    Webcam = 1
    Software = 2
    Unknown = 3


class EMediaAudioCaptureDeviceFilter(enum.Enum):
    Card = 0
    Unknown = 1
    Microphone = 2
    Software = 3


class EMediaPlayerTrack(enum.Enum):
    Subtitle = 0
    Caption = 1
    Metadata = 2


class EMediaSoundChannels(enum.Enum):
    Stereo = 0
    Surround = 1
