from __future__ import annotations # type: ignore
from unrealsdk import unreal
import typing
import enum


from . import engine



class MeshReconstructorBase(unreal.UObject):

    def StopReconstruction(self): ...
    def StartReconstruction(self): ...
    def PauseReconstruction(self): ...
    def IsReconstructionStarted(self, ReturnValue: bool) -> bool: ...
    def IsReconstructionPaused(self, ReturnValue: bool) -> bool: ...
    def DisconnectMRMesh(self): ...
    def ConnectMRMesh(self, Mesh: MRMeshComponent): ...


class MRMeshComponent(engine.PrimitiveComponent):
    Material: engine.MaterialInterface
    bCreateMeshProxySections: bool
    bUpdateNavMeshOnMeshUpdate: bool
    BodySetups: unreal.WrappedArray[engine.BodySetup]
    def IsConnected(self, ReturnValue: bool) -> bool: ...
    def ForceNavMeshUpdate(self): ...
    def Clear(self): ...


class MRMeshConfiguration: ...
