from __future__ import annotations # type: ignore
from unrealsdk import unreal
import typing
import enum


from . import engine



class VaRestJsonObject(unreal.UObject):

    def SetStringField(self, FieldName: str, StringValue: str): ...
    def SetStringArrayField(self, FieldName: str, StringArray: unreal.WrappedArray[str]): ...
    def SetObjectField(self, FieldName: str, JsonObject: VaRestJsonObject): ...
    def SetObjectArrayField(self, FieldName: str, ObjectArray: unreal.WrappedArray[VaRestJsonObject]): ...
    def SetNumberField(self, FieldName: str, Number: float): ...
    def SetNumberArrayField(self, FieldName: str, NumberArray: unreal.WrappedArray[float]): ...
    def SetField(self, FieldName: str, JsonValue: VaRestJsonValue): ...
    def SetBoolField(self, FieldName: str, InValue: bool): ...
    def SetBoolArrayField(self, FieldName: str, BoolArray: unreal.WrappedArray[bool]): ...
    def SetArrayField(self, FieldName: str, inArray: unreal.WrappedArray[VaRestJsonValue]): ...
    def Reset(self): ...
    def RemoveField(self, FieldName: str): ...
    def MergeJsonObject(self, InJsonObject: VaRestJsonObject, Overwrite: bool): ...
    def HasField(self, FieldName: str, ReturnValue: bool) -> bool: ...
    def GetStringField(self, FieldName: str, ReturnValue: str) -> str: ...
    def GetStringArrayField(self, FieldName: str, ReturnValue: unreal.WrappedArray[str]) -> unreal.WrappedArray[str]: ...
    def GetObjectField(self, FieldName: str, ReturnValue: VaRestJsonObject) -> VaRestJsonObject: ...
    def GetObjectArrayField(self, FieldName: str, ReturnValue: unreal.WrappedArray[VaRestJsonObject]) -> unreal.WrappedArray[VaRestJsonObject]: ...
    def GetNumberField(self, FieldName: str, ReturnValue: float) -> float: ...
    def GetNumberArrayField(self, FieldName: str, ReturnValue: unreal.WrappedArray[float]) -> unreal.WrappedArray[float]: ...
    def GetFieldNames(self, ReturnValue: unreal.WrappedArray[str]) -> unreal.WrappedArray[str]: ...
    def GetField(self, FieldName: str, ReturnValue: VaRestJsonValue) -> VaRestJsonValue: ...
    def GetBoolField(self, FieldName: str, ReturnValue: bool) -> bool: ...
    def GetBoolArrayField(self, FieldName: str, ReturnValue: unreal.WrappedArray[bool]) -> unreal.WrappedArray[bool]: ...
    def GetArrayField(self, FieldName: str, ReturnValue: unreal.WrappedArray[VaRestJsonValue]) -> unreal.WrappedArray[VaRestJsonValue]: ...
    def EncodeJsonToSingleString(self, ReturnValue: str) -> str: ...
    def EncodeJson(self, ReturnValue: str) -> str: ...
    def DecodeJson(self, JsonString: str, ReturnValue: bool) -> bool: ...
    def ConstructJsonObject(self, WorldContextObject: unreal.UObject, ReturnValue: VaRestJsonObject) -> VaRestJsonObject: ...


class VaRestJsonValue(unreal.UObject):

    def IsNull(self, ReturnValue: bool) -> bool: ...
    def GetTypeString(self, ReturnValue: str) -> str: ...
    def GetType(self, ReturnValue: int) -> int: ...
    def ConstructJsonValueString(self, WorldContextObject: unreal.UObject, StringValue: str, ReturnValue: VaRestJsonValue) -> VaRestJsonValue: ...
    def ConstructJsonValueObject(self, WorldContextObject: unreal.UObject, JsonObject: VaRestJsonObject, ReturnValue: VaRestJsonValue) -> VaRestJsonValue: ...
    def ConstructJsonValueNumber(self, WorldContextObject: unreal.UObject, Number: float, ReturnValue: VaRestJsonValue) -> VaRestJsonValue: ...
    def ConstructJsonValueBool(self, WorldContextObject: unreal.UObject, InValue: bool, ReturnValue: VaRestJsonValue) -> VaRestJsonValue: ...
    def ConstructJsonValueArray(self, WorldContextObject: unreal.UObject, inArray: unreal.WrappedArray[VaRestJsonValue], ReturnValue: VaRestJsonValue) -> VaRestJsonValue: ...
    def AsString(self, ReturnValue: str) -> str: ...
    def AsObject(self, ReturnValue: VaRestJsonObject) -> VaRestJsonObject: ...
    def AsNumber(self, ReturnValue: float) -> float: ...
    def AsBool(self, ReturnValue: bool) -> bool: ...
    def AsArray(self, ReturnValue: unreal.WrappedArray[VaRestJsonValue]) -> unreal.WrappedArray[VaRestJsonValue]: ...


class VaRestLibrary(engine.BlueprintFunctionLibrary):

    def PercentEncode(self, Source: str, ReturnValue: str) -> str: ...
    def Base64EncodeData(self, Data: unreal.WrappedArray[int], Dest: str, ReturnValue: bool) -> bool: ...
    def Base64Encode(self, Source: str, ReturnValue: str) -> str: ...
    def Base64DecodeData(self, Source: str, Dest: unreal.WrappedArray[int], ReturnValue: bool) -> bool: ...
    def Base64Decode(self, Source: str, Dest: str, ReturnValue: bool) -> bool: ...


class VaRestRequestJSON(unreal.UObject):
    ResponseContent: str
    bIsValidJsonResponse: bool
    RequestJsonObj: VaRestJsonObject
    ResponseJsonObj: VaRestJsonObject
    def SetVerb(self, Verb: ERequestVerb): ...
    def SetStringRequestContent(self, Content: str): ...
    def SetResponseObject(self, JsonObject: VaRestJsonObject): ...
    def SetRequestObject(self, JsonObject: VaRestJsonObject): ...
    def SetHeader(self, HeaderName: str, HeaderValue: str): ...
    def SetCustomVerb(self, Verb: str): ...
    def SetContentType(self, ContentType: ERequestContentType): ...
    def SetBinaryRequestContent(self, Content: unreal.WrappedArray[int]): ...
    def SetBinaryContentType(self, ContentType: str): ...
    def ResetResponseData(self): ...
    def ResetRequestData(self): ...
    def ResetData(self): ...
    def RemoveTag(self, Tag: str, ReturnValue: int) -> int: ...
    def ProcessURL(self, URL: str): ...
    def HasTag(self, Tag: str, ReturnValue: bool) -> bool: ...
    def GetUrl(self, ReturnValue: str) -> str: ...
    def GetStatus(self, ReturnValue: ERequestStatus) -> ERequestStatus: ...
    def GetResponseObject(self, ReturnValue: VaRestJsonObject) -> VaRestJsonObject: ...
    def GetResponseHeader(self, HeaderName: str, ReturnValue: str) -> str: ...
    def GetResponseCode(self, ReturnValue: int) -> int: ...
    def GetRequestObject(self, ReturnValue: VaRestJsonObject) -> VaRestJsonObject: ...
    def GetAllResponseHeaders(self, ReturnValue: unreal.WrappedArray[str]) -> unreal.WrappedArray[str]: ...
    def ConstructRequestExt(self, WorldContextObject: unreal.UObject, Verb: ERequestVerb, ContentType: ERequestContentType, ReturnValue: VaRestRequestJSON) -> VaRestRequestJSON: ...
    def ConstructRequest(self, WorldContextObject: unreal.UObject, ReturnValue: VaRestRequestJSON) -> VaRestRequestJSON: ...
    def Cancel(self): ...
    def ApplyURL(self, URL: str, Result: VaRestJsonObject, WorldContextObject: unreal.UObject, LatentInfo: engine.LatentActionInfo): ...
    def AddTag(self, Tag: str): ...


class VaRestCallResponse:
    Request: VaRestRequestJSON
    WorldContextObject: unreal.UObject



class EVaJson(enum.Enum):
    Null = 0
    String = 1
    Boolean = 2


class ERequestStatus(enum.Enum):
    Processing = 0
    Failed = 1
    Succeeded = 2


class ERequestContentType(enum.Enum):
    x_www_form_urlencoded_body = 0
    ERequestContentType_MAX = 1
    json = 2


class ERequestVerb(enum.Enum):
    POST = 0
    CUSTOM = 1
    PUT = 2
